class Config(object):
    YNAB_URL = '[POPULATE WITH YNAB API URL]'
    DATABASE_URL = '[POPULATE WITH DATABASE PATH]'
    BEARER = '[POPULATE WITH UNIQUE CODE FROM API ACCOUNT]'
    ERROR_LOGGING_FILE = '[POPULATE WITH ERROR LOG FILE NAME]'